# Generated by Django 5.0.6 on 2024-05-21 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='answeruser',
            old_name='answer_id',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='answeruser',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='poll',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='poll_id',
            new_name='poll',
        ),
    ]
